services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    command: bun run start:dev
    environment:
      - NODE_ENV=development
    expose:
      - "8080"  # exposes port to other services, not the host
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "9974:80"  # expose only nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    expose:
      - "5432"  # exposes port to other services, not the host
    ports:
      - "5432:5432"  # expose postgres to the host

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    # ports:
    #   - "5050:80"  # expose pgAdmin to the host
    expose:
      - "80"  # exposes port to other services, not the host
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  postgres_data_test: