version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '8081:8080'
    volumes:
      - .:/app/src
    command: bun run start:dev
    environment:
      - NODE_ENV=development